version: "3"

services:
  db-postgres-upload:
    image: postgres:alpine
    ports:
      - "5431:5432"
    container_name: "db-postgres-upload"
    restart: always
    volumes:
      - ./db-postgres-upload:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admuser
      POSTGRES_PASSWORD: admuser
volumes:
  db-postgres-teste:
    